apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-api
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/EugeneKozyrev/chart.git'
      targetRevision: 'v1.0.1'
      path: '.'
      helm:
        valueFiles:
          - $values/simple-api/dev/values.yaml
        ignoreMissingValueFiles: true
    - repoURL: 'https://github.com/EugeneKozyrev/helm.git'
      targetRevision: 'master'
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true